# Generated by Django 4.1.7 on 2023-03-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=20)),
                ('Branch', models.CharField(max_length=40)),
                ('IFSC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=20)),
                ('CAcno', models.BigIntegerField()),
                ('CAddr', models.CharField(max_length=200)),
                ('Requirement', models.CharField(max_length=20)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.bank')),
            ],
        ),
    ]
